'''
    1.此文件存放语言模板,在用户选择语言后通过get_text获取用户选择语言下的文字输出
    2.提供get_text方法
'''

# 存储用户语言选择
user_language = {}

# 语言模板
language_templates = {
    'en': {
        'start': "Welcome to the U Card Bot! Please choose your language to begin.",
        'email_prompt': "Please enter your email to bind your U card:",
        'login_success': "Login successful! Please select an option below:",
        'transaction_prompt': "View Transaction History💸",
        'transaction_fail': "Failed to get transactions. Please try again later.",
        'transaction_page': "Transaction History (Page {}):",
        'transaction_time': "🕒 Transaction Time:",
        'transaction_id': "🆔 Transaction ID:",
        'related_transaction_id': "🔗 Related Transaction ID:",
        'confirmation_time': "⌚ Confirmation Time:",
        'transaction_amount': "💰 Transaction Amount:",
        'accounting_amount': "💵 Settlement Amount:",
        'surcharge_amount': "💸 Surcharge:",
        'merchant_name': "🏢 Merchant Name:",
        'merchant_region': "🌍 Merchant Region:",
        'business_type': "📝 Business Type:",
        'transaction_status': "✓ Transaction Status:",
        'status_description': "📋 Status Description:",
        'card_number': "💳 Card Number:",
        'balance_prompt': "View Balance History💰",
        'balance_fail': "Failed to get balance history. Please try again later.",
        'balance_page': "Balance History (Page {}):",
        'balance_after': "💰 Balance After:",
        'next_page': "Next →",
        'prev_page': "← Back",
        'choose_language': "Please select your language:",
        'invalid_email': "Invalid email format. Please try again.",
        'verification_sent': "Verification code has been sent to your email. Please enter the code:",
        'verification_fail': "Failed to send verification code. Please try again.",
        'verification_error': "Incorrect verification code. Please enter your email again:",
        'unbind_success': "Successfully unbound! Please use /start command to start using the bot.",
        'unbind_fail': "Failed to unbind. Please try again later.",
        'select_operation': "Please select an operation:",
        'no_transactions': "No transaction records found.",
        'no_balance_records': "No balance records found.",
        'unbind': "Unbind🔓",
        'divider': "=" * 30,
        'after_language_selection_menu':"The menu options are as follows:\n"+
                                        "Bind and query👁️ - After binding the U card, you can perform query operations\n",
        'InlineKeyboardButton_loginsearch':'Bind U card🔒',
        'InlineKeyboardButton_help':"Help🔭",
        'InlineKeyboardButton_url':"Official website🔗",
        'confirm_language_selection':'Selected language: English\n' + 'Continue, click➡️',
        'back_bind':'Return to menu, re-bind card🔁',
        'login_persistence':'You have bound a U card, and you can perform other operations after unbinding❗'
    },
    'jp': {
        'start': "Uカードボットへようこそ!言語を選択してください。",
        'email_prompt': "Uカードをバインドするためにメールアドレスを入力してください:",
        'login_success': "ログイン成功！以下のオプションから選択してください:",
        'transaction_prompt': "取引履歴を表示💸",
        'transaction_fail': "取引履歴の取得に失敗しました。後でもう一度お試しください。",
        'transaction_page': "取引履歴（ページ {}):",
        'transaction_time': "🕒 時間:",
        'amount_local': None,
        'amount_usd': None,
        'merchant': None,
        'status': None,
        'next_page': "次へ →",
        'prev_page': "← 戻る",
        'choose_language': "言語を選択してください:",
        'invalid_email': "メールアドレスの形式が無効です。もう一度お試しください。",
        'balance_prompt': "残高履歴を表示💰",
        'balance_fail': "残高履歴の取得に失敗しました。後でもう一度お試しください。",
        'balance_after': "💰 残高:",
        'card_number': "💳 カード番号:",
        'balance_page': "残高履歴（ページ {}):",
        'verification_sent': "認証コードをメールに送信しました。コードを入力してください:",
        'verification_fail': "認証コードの送信に失敗しました。もう一度お試しください。",
        'verification_error': "認証コードが間違っています。メールアドレスを再入力してください:",
        'unbind_success': "バインド解除に成功しました！ /start コマンドでボットの使用を開始してください。",
        'unbind_fail': "バインド解除に失敗しました。後でもう一度お試しください。",
        'select_operation': "操作を選択してください:",
        'no_transactions': "取引記録が見つかりません。",
        'no_balance_records': "残高記録が見つかりません。",
        'unbind': "バインド解除🔓",
        'business_type': "📝 取引種類:",
        'confirmation_time': "⌚ Confirmation Time:",
        'surcharge': None,
        'region': None,
        'status_description': "📋 Status Description:",
        'transaction_id': "🆔 取引ID:",
        'related_transaction_id': "🔗 関連取引ID:",
        'transaction_time': "🕒 取引時間:",
        'confirmation_time': "⌚ 決済時間:",
        'transaction_amount': "💰 取引金額:",
        'accounting_amount': "💵 決済金額:",
        'surcharge_amount': "💸 手数料:",
        'merchant_name': "🏢 加盟店名:",
        'merchant_region': "🌍 加盟店地域:",
        'transaction_status': "✓ 取引状態:",
        'status_description': "📋 状態詳細:",
        'card_number': "💳 カード番号:",
        'divider': "=" * 30,
        'after_language_selection_menu':"メニューオプションは以下の通りです：\n"+
                                        "バインドしてクエリ👁️ - Uカードをバインドした後、クエリ操作を行うことができます\n",
        'InlineKeyboardButton_loginsearch':'uカードをバインドします🔒',
        'InlineKeyboardButton_help':"助けを得る🔭",
        'InlineKeyboardButton_url':"公式ウェブサイト🔗",
        'confirm_language_selection':'選択した言語: 日本語\n' + '操作を続けて、クリックします➡️',
        'back_bind':'メニューに戻る、カードを再びバインドする🔁',
        'login_persistence':'あなたはUカードをバインドしました、あなたはそれを解除した後、他の操作を実行できます❗'
    },
    'zh_cn': {
        'start': "欢迎使用 U Card Bot!请选择您的语言以开始。",
        'email_prompt': "请输入您的邮箱以绑定 U 卡：",
        'password_prompt': "请输入您的密码：",
        'login_success': "登录成功！请选择以下选项：",
        'login_fail': "密码错误。请重试。",
        'transaction_prompt': "查看交易记录💸",
        'transaction_fail': "获取交易记录失败。请稍后再试。",
        'Loading': "加载中...",
        'bind_first': "请先通过点击 /start 绑定您的 U 卡。",
        'click_start': "请点击 /start 开始。",
        'records_found': "找到 {} 条记录：",
        'transaction_page': "交易记录（第 {} 页）：",
        'transaction_time': "🕒 时间：",
        'amount_local': None,
        'amount_usd': None,
        'type': " 类型：",
        'status': None,
        'merchant': None,
        'region': None,
        'surcharge': None,
        'next_page': "下一页 →",
        'prev_page': "← 上一页",
        'choose_language': "请选择您的语言 / 言語を選択してください:",
        'invalid_email': "邮箱格式无效。请重试。",
        'balance_prompt': "查看余额记录💰",
        'balance_fail': "获取余额记录失败。请稍后再试。",
        'balance_result': "当前余额：{} 美元",
        'balance_after': "💰 余额:",
        'card_number': "💳 卡号：",
        'transaction_type': " 类型：",
        'business_type': "📝 业务类型:",
        'balance_page': "余额记录（第 {} 页）：",
        'verification_sent': "验证码已发送到您的邮箱，请输入验证码：",
        'verification_fail': "发送验证码失败，请重试。",
        'verification_error': "验证码错误，请重新输入邮箱：",
        'unbind_success': "解绑成功！请重新使用 /start 命令开始使用机器人。",
        'unbind_fail': "解绑失败，请稍后重试。",
        'select_operation': "请选择操作：",
        'no_transactions': "没有找到交易记录",
        'no_balance_records': "没有找到余额记录",
        'unbind': "解除绑定🔓",
        'business_type': "📝 Business Type:",
        'confirmation_time': "⌚ Confirmation Time:",
        'surcharge': None,
        'region': None,
        'status_description': "📋 Status Description:",
        'transaction_id': "🆔 交易ID:",
        'related_transaction_id': "🔗 关联交易ID:",
        'transaction_time': "🕒 交易时间:",
        'confirmation_time': "⌚ 入账时间:",
        'transaction_amount': "💰 交易金额:",
        'accounting_amount': "💵 入账金额:",
        'surcharge_amount': "💸 手续费:",
        'merchant_name': "🏢 商户名称:",
        'merchant_region': "🌍 商户地区:",
        'transaction_status': "✓ 交易状态:",
        'status_description': "📋 状态描述:",
        'card_number': "💳 卡号:",
        'divider': "=" * 30,
        'after_language_selection_menu':"菜单选项如下：\n"+
                                        "绑定并查询👁️ - 绑定U卡后,可进行查询操作\n",
        'InlineKeyboardButton_loginsearch':'绑定U卡🔒',
        'InlineKeyboardButton_help':"帮助🔭",
        'InlineKeyboardButton_url':"官方网址🔗",
        'confirm_language_selection':'选择的语言: 简体中文\n' + '继续操作,点击➡️',
        'back_bind':'返回菜单,重新绑卡🔁',
        'login_persistence':'你已绑定U卡,解绑后可进行其他操作❗',
        'code_table':'USTD:美元' + ' '*2 + 'CHY:人民币'+ ' '*2 + 'HKD:港元\n' +
                    'JPY:日元' + ' '*2 + 'EUR:欧元' + ' '*2 + 'GBP:英镑\n' +
                    'AUD:澳大利亚元' + ' '*2 + 'CAD:加拿大元' + ' '*2 + 'SGD:新加披元\n' +
                    'CHF:瑞士法郎' + ' '*2 + 'NZD:新西兰元' + ' '*2 + 'PHP:菲律宾比索\n' +
                    'VND:越南盾' + ' '*2 + 'MYR:马来西亚林吉特' + ' '*2 + 'THB:泰铢\n' +
                    'IDR:印度尼西亚卢比' + ' '*2 + 'KRW:韩元' + ' '*2 + 'NGN:尼日利亚奈拉\n' +
                    'INR:印度卢比' + ' '*2 + 'AED:阿联酋迪拉姆' + ' '*2 + 'KHR:柬埔寨瑞尔\n' +
                    'TWD:新台币' + ' '*2 + 'KZT:哈萨克斯坦坚戈' + ' '*2 + 'MXN:墨西哥比索\n' +
                    'TRY:土耳其里拉' + ' '*2 + 'MOP:澳门币' + ' '*2 + 'PKR:巴基斯坦卢比\n' +
                    'ARS:阿根廷比索' + ' '*2 + 'MDL:摩尔多瓦列伊' + ' '*2 + 'ZMW:赞比亚克瓦查\n' +
                    'IQD:伊拉克第纳尔' + ' '*2 + 'DZD:阿尔及利亚第纳尔' + ' '*2 + 'ALL:阿尔巴尼亚列克\n',
    },
    'zh_tw': {
        'start': "歡迎使用 U Card Bot！請選擇您的語言以開始。",
        'email_prompt': "請輸入您的電子郵件以綁定 U 卡：",
        'password_prompt': "請輸入您的密碼：",
        'login_success': "登入成功！請選擇以下選項：",
        'login_fail': "密碼錯誤。請重試。",
        'transaction_prompt': "查看交易記錄💸",
        'transaction_fail': "取得交易記錄失敗。請稍後再試。",
        'Loading': "載入中...",
        'bind_first': "請先通過點擊 /start 綁定您的 U 卡。",
        'click_start': "請點擊 /start 開始。",
        'records_found': "找到 {} 條記錄：",
        'transaction_page': "交易記錄（第 {} 頁）：",
        'transaction_time': "🕒 時間：",
        'amount_local': None,
        'amount_usd': None,
        'type': " 種類：",
        'status': None,
        'merchant': None,
        'region': None,
        'surcharge': None,
        'next_page': "下一頁 →",
        'prev_page': "← 上一頁",
        'choose_language': "請選擇您的語言 / 言語を選択してください:",
        'invalid_email': "電子郵件格式無效。請重試。",
        'balance_prompt': "查看餘額記錄💰",
        'balance_fail': "獲取餘額記錄失敗，請稍後重試",
        'balance_after': "💰 餘額:",
        'card_number': "💳 卡號:",
        'transaction_type': " 種類：",
        'business_type': "📝 業務類型:",
        'balance_page': "餘額記錄（第 {} 頁）：",
        'verification_sent': "驗證碼已發送到您的郵箱，請輸入驗證碼：",
        'verification_fail': "發送驗證碼失敗，請重試。",
        'verification_error': "驗證碼錯誤，請重新輸入郵箱：",
        'unbind_success': "解綁成功！請重新使用 /start 命令開始使用機器人。",
        'unbind_fail': "解綁失敗，請稍後重試。",
        'select_operation': "請選擇操作：",
        'no_transactions': "沒有找到交易記錄",
        'no_balance_records': "沒有找到餘額記錄",
        'unbind': "解除綁定🔓",
        'business_type': "📝 Business Type:",
        'confirmation_time': "⌚ Confirmation Time:",
        'surcharge': None,
        'region': None,
        'status_description': "📋 Status Description:",
        'transaction_id': "🆔 交易ID:",
        'related_transaction_id': "🔗 關聯交易ID:",
        'transaction_time': "🕒 交易時間:",
        'confirmation_time': "⌚ 入賬時間:",
        'transaction_amount': "💰 交易金額:",
        'accounting_amount': "💵 入賬金額:",
        'surcharge_amount': "💸 手續費:",
        'merchant_name': "🏢 商戶名稱:",
        'merchant_region': "🌍 商戶地區:",
        'transaction_status': "✓ 交易狀態:",
        'status_description': "📋 狀態描述:",
        'card_number': "💳 卡號:",
        'divider': "=" * 30,
        'after_language_selection_menu':"菜單選項如下：\n"+
                                        "綁定並查詢👁️ - 綁定U卡後，可進行查詢操作\n",
        'InlineKeyboardButton_loginsearch':'綁定U卡🔒',
        'InlineKeyboardButton_help':"幫助🔭",
        'InlineKeyboardButton_url':"官方網址🔗",
        'confirm_language_selection':'選擇的語言: 繁體中文\n' + '繼續操作,點擊➡️',
        'back_bind':'返回菜單,重新綁卡🔁',
        'login_persistence':'您已綁定U卡,解綁後可進行其他操作❗'
    }
}

def get_text(user_id: int, key: str) -> str:
    """获取对应语言的文本"""
    lang = user_language.get(user_id, 'en')
    return language_templates[lang][key] 